### PR TITLE
Rename own_state and peer_state to account_data and peer_data

### PR DESCRIPTION
**Pull request by Valodim**
As discussed previously. I'm not sure if this is a super great idea yet, but creating this PR as a basis for discussion.

### CODE REVIEW

**Comment by Valodim** [comment]
I'm not sure about "peer data", but renaming the "own" stuff to "account" stuff feels like an improvement to me

**Comment by dkg** [comment]
I think this reorganization is great, but it doesn't go far enough.

What if we made `account_data` itself a table indexed by account e-mail address, in the same way that `peer_data` is a table indexed by peer e-mail address?

At that point, we can remove some of the caveats like "as though it were only capable of controlling a single e-mail account" and everything becomes neatly more parallel.

**Comment by dkg** [comment]
@azul points out that we could go even simpler, and just have two tables for the MUA, both indexed by e-mail address:

 * `accounts`
 * `peers`

then we don't need the words `_data` or `_state` at all.

**Comment by azul** [comment]
superseeded by #204

**Pull request closed without merging**
