### PR TITLE
Blogpost to submit to ACM xrds

### PR DESCRIPTION
**Pull request by lefherz**
Comments on the ongoing work in this PR please.

Deadline for the first version: March 6th.

 ### To do:

* [x] write chapter "How to Bring Encryption to the Many".
* [x] delete "pitfalls of centralization" and "Free Software as technological advancement".
* [x] find better titles.
* [ ] author bios.
* [ ] get thumbs up by everyone mentioned & involved
  * [x] @karissa 
  * [ ] @dkg 
  * [ ] @valodim
  * [x] @hpk42 
  * [x] @r10s 
* [ ] build blog structure for the website based on https://stackoverflow.com/questions/1576340/using-sphinx-to-write-personal-websites-and-blogs
* [ ] adjust date of the folders to publishing day
* [ ] add relevant links to the text
* [ ] include images
  * [ ] of the simplest possible UI in contrast to complex key management
  * [ ] autocrypt happy example
  * [ ] the logo or something, I guess

### CODE REVIEW

**Comment by karissa** [comment]
bio: Karissa McKelvey is an open source software developer, writer, project manager, and activist supporting an equitable web. She is a Software Engineer at Digital Democracy and board member of Code for Science and Society. Formerly a data scientist, her work studying online political communication resulted in multiple peer-reviewed papers and press in outlets such as NPR and the Wall Street Journal.

**Comment by r10s** [comment]
thums up from me :+1:

**Comment by karissa** [comment]
I say no image is necessary, let's just go for it!

**Comment by hpk42** [comment]
bio: 
Holger is a senior developer, researcher and trainer of programming systems and tools.  Holger completed a diploma degree with magna cum lauda in 1998 with a major focus on cryptography under the late Professor and privacy expert Andreas Pfitzmann.  He is the principal author of popular testing and packaging tools in the Python programming ecosystem which each have their own independent community by now. He has given over forty conference talks, including a keynote talk at a large Programming conference in 2013 about "The return of P2P computing".

**Comment by lefherz** [comment]
Emil Lefherz is a technology philosopher, musician, and Free Software activist. He joined Autocrypt in 2017, so he doesn't have to explain Key Management anymore at Cryptoparties.

**Comment by lefherz** [comment]
I sent the article to ACM. We can incorporate the changes they suggest in the version on our website, btw - so I suggest to leave this PR open for now, as there are still a few things missing, especially the consent of some people to actually publishing it.

**Comment by hpk42** [comment]
nothing happening so let's just close this.  I'll to bring some XRDMS editions i still have to 35c3, so they can lie around ;) already gave some to several folks.

**Pull request closed without merging**
