### PR TITLE
propose initial press team policy

### PR DESCRIPTION
**Pull request by dkg**

### CODE REVIEW

**Comment by dkg** [comment]
fwiw, merging this into master doesen't mean the policy is perfect, it just means it's good enough to work with for now.  i hope we'll see changes as we figure out what works.

**Comment by dkg** [comment]
See also #308

**Comment by r10s** [comment]
looks good to me, i think this can be merged and refined later.

**Comment by hpk42** [comment]
I started from your branch but diverged enough to do an alternative #312 
that "press-team" alias is currently matching what is in the #312. Note it's press-team, not "press"

**Comment by lefherz** [comment]
I like #312, because it is text which you actually want to put on a website ;) 
But this one has a justification too, of course, transparency for the community.

Actually, I'd put #312 somewhere visible in contact.rst, and put a link below, which links to these #309 specifications, if anyone is interested they can find them.

**Comment by dkg** [comment]
I'm closing this because i think #312 does everytihng this one does, but has more consensus around it.

**Pull request closed without merging**
