### PR TITLE
be more specific and replace 'piggybacking'

### PR DESCRIPTION
**Pull request by karissa**
just in case there weren't enough changes in the past week, here's another two cents.

piggybacking is colloquial and non-native speakers with a lower level will likely have trouble with it.

### CODE REVIEW

**Comment by Valodim** [comment]
I think hpk's use of "encryption capabilities" was a way to avoid using "keys" here :) your version also slightly loses the notion that the negotiation happens along regular emails, they are not specifically sent for this purpose.

How about this?:

> It specifies how e-mail programs can transparently negotiate encryption capabilities in regular e-mail communication.

**Comment by karissa** [comment]
are keys not transferred? Happy to change it but it sounds like you're avoiding something that people will find out anyway

**Comment by Valodim** [comment]
Keys are transferred, of course. But for users this is an implementation detail, and for techies it's an obvious implication from "negotiate encryption". Users don't need to know what a "key" is to be able to use Autocrypt, or at least that is one of our goals. :)

**Comment by karissa** [comment]
ok removed the keys part.

**Pull request merged**
