### PR TITLE
K-9 Mail v5.700 supports setup messages

### PR DESCRIPTION
**Pull request by wodry**
K-9 Mail v5.700 "Added support for Autocrypt setup message" (https://github.com/k9mail/k-9/releases/tag/5.700)
See pull request "Autocrypt Setup Message sending" (https://github.com/k9mail/k-9/pull/3342)

### CODE REVIEW

**Comment by wodry** [comment]
I have not tested the real functionality of K-9 Mail, since I do not use telephone mini computers. This PR is only based on the sources given in OP. Maybe someone can test?

**Comment by missytake** [comment]
It works on 5.700 onwards, I tested it. But the default version F-Droid delivers is still 5.600. Not sure why.

**Comment by missytake** [comment]
5.600 is the latest stable version, so it's not in stable yet.

**Comment by wodry** [comment]
Ah interesting, could not imagine a "release" is not stable or beta release. They say _we’ll spend some time focusing on fixing bugs reported by beta testers, and then we’ll release the next stable version of K-9 Mail, 5.800._ half a year ago. (https://k9mail.app/2020/06/01/Whats-Up-With-K-9-Mail.html)

**Comment by wodry** [comment]
5.7x is still not stable, closing.

**Pull request closed without merging**
