### PR TITLE
Some CSS to make the dev-status table more legible

### PR DESCRIPTION
**Pull request by BjarniRunar**
This rotates the column headings 90°, making the colunms narrower, so things actually fit on smaller screens. Also adds subtle striping to the table to make it easier to scan.

image

### CODE REVIEW

**Comment by lefherz** [comment]
Wow, this is awesome. I always hated that scroll bar, but didn't think of that solution.

**Comment by BjarniRunar** [comment]
I'll do the rebase dance :-)

**Comment by dkg** [comment]
fwiw, i think an angled rotation of less than 90°, and in the opposite direction would be better.

see the examples in https://css-tricks.com/rotated-table-column-headers/

i'll supply a patch if @BjarniRunar doesn't want to do it :)

**Comment by dkg** [comment]
interesting, Chromium 76.0.3809.100-1 doesn't appear to support the `writing-mode` property, but Firefox 70.0 does. (this is in contradiction to [the MDN docs for `writing-mode`](https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode)

**Comment by dkg** [comment]
I did #421 based on this idea (and incorporating bjarni's initial work).  Please consider merging that one instead.

**Comment by dkg** [comment]
I think this has been superceded by #421 , which is now merged.  Thanks for the inspiration, @BjarniRunar !

**Pull request closed without merging**
