### PR TITLE
Bot takes Alice´s address from the from attribute

### PR DESCRIPTION
**Pull request by titusz**

### CODE REVIEW

**Comment by titusz** [comment]
Ok it seems i got this wrong.... the to-attribute is meant to refer to the Autocrypt header to-attribute?  Isn´t that redundant with the mail header from attribute?

**Comment by Valodim** [comment]
The from header can change, e.g. in mailing lists that forward in a dmarc compatible ways

**Comment by titusz** [comment]
Well yes that makes sense ... In any case malicious user could advertise wrong autoencrypt headers in the name of others .... but i guess there is not much that can be done about that.

**Comment by Valodim** [comment]
They can, but such troubles should be mitigated by spam filters. And as a targeted attack, it's not exactly covert :)

**Pull request closed without merging**
